name: Deploy FE app to Azure App Services

on:
  push:
    branches: [ 'main' ]
    paths: [ 'frontend/**' ]

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_build_command: "npm run build"
          app_location: "frontend"
          api_location: ""
          output_location: "dist"
        env:
          VITE_API_URL: "https://func-inference-classification-dev.azurewebsites.net/api/"
          VITE_API_TOKEN: ${{ secrets.API_TOKEN }}